import React from 'react';
import {useCurrentFrame} from 'remotion';
import {numberPunch, staggerStack} from '../motion/presets';
import {FEE_COLORS} from '../motion/tokens';

export const EvidenceNumber: React.FC<{claim: string; value: string | number; unit?: string; period?: string; source?: string; start?: number}> = ({claim, value, unit, period, source, start = 0}) => {
  const frame = useCurrentFrame();
  const style = numberPunch(frame, start);
  return <div style={{...style, position: 'absolute', left: 80, top: 160, width: 900}}><div style={{fontSize: 25, textTransform: 'uppercase', letterSpacing: 3, color: FEE_COLORS.muted}}>{claim}</div><div style={{display: 'flex', alignItems: 'baseline', gap: 16, marginTop: 20}}><div style={{fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 155, lineHeight: .8}}>{value}</div>{unit ? <div style={{fontSize: 32, color: FEE_COLORS.teamA}}>{unit}</div> : null}</div>{period ? <div style={{fontSize: 20, color: FEE_COLORS.muted, marginTop: 28}}>{period}</div> : null}{source ? <div style={{fontSize: 15, color: FEE_COLORS.muted, marginTop: 8}}>Source · {source}</div> : null}</div>;
};

export const ComparisonBlock: React.FC<{left: {label: string; value: string | number}; right: {label: string; value: string | number}; delta?: string; start?: number}> = ({left, right, delta, start = 0}) => <div style={{position: 'absolute', left: 100, right: 100, top: 240, display: 'flex', alignItems: 'center', justifyContent: 'space-between'}}><div style={{...staggerStack(useCurrentFrame(), 0, start)}}><div style={{fontSize: 25, color: FEE_COLORS.teamA}}>{left.label}</div><div style={{fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 120}}>{left.value}</div></div><div style={{fontSize: 25, color: FEE_COLORS.muted}}>VS</div><div style={{...staggerStack(useCurrentFrame(), 1, start), textAlign: 'right'}}><div style={{fontSize: 25, color: FEE_COLORS.teamB}}>{right.label}</div><div style={{fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 120}}>{right.value}</div></div>{delta ? <div style={{position: 'absolute', left: '50%', top: 175, translate: '-50% 0', color: FEE_COLORS.accent, fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 46}}>{delta}</div> : null}</div>;

export const TrendStrip: React.FC<{items: Array<{opponent: string; result: string; score: string; tone?: string}>; start?: number}> = ({items, start = 0}) => <div style={{position: 'absolute', left: 80, right: 80, top: 330, display: 'flex', justifyContent: 'space-between'}}>{items.map((item, index) => <div key={`${item.opponent}-${index}`} style={{...staggerStack(useCurrentFrame(), index, start), width: 180, borderTop: `6px solid ${item.tone === 'loss' ? FEE_COLORS.out : item.tone === 'draw' ? FEE_COLORS.accent : FEE_COLORS.teamA}`, paddingTop: 12}}><div style={{fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 44}}>{item.result}</div><div style={{fontSize: 18, color: FEE_COLORS.muted}}>{item.score}</div><div style={{fontSize: 18, marginTop: 16}}>{item.opponent}</div></div>)}</div>;

export const H2HTimeline: React.FC<{items: Array<{year: string; result: string}>; start?: number}> = ({items, start = 0}) => <div style={{position: 'absolute', left: 120, right: 120, top: 300, display: 'flex', justifyContent: 'space-between', borderTop: `4px solid ${FEE_COLORS.ink}`, paddingTop: 24}}>{items.map((item, index) => <div key={item.year} style={{...staggerStack(useCurrentFrame(), index, start), textAlign: 'center'}}><div style={{width: 28, height: 28, borderRadius: '50%', background: item.result === 'DRAW' ? FEE_COLORS.accent : item.result === 'A WIN' ? FEE_COLORS.teamA : FEE_COLORS.teamB, margin: '0 auto 12px'}} /><div style={{fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 24}}>{item.year}</div><div style={{fontSize: 18, color: FEE_COLORS.muted, marginTop: 6}}>{item.result}</div></div>)}</div>;

export const AvailabilityBoard: React.FC<{items: Array<{name: string; status: string; tone: 'available' | 'doubtful' | 'out'}>; start?: number}> = ({items, start = 0}) => <div style={{position: 'absolute', left: 100, right: 100, top: 250, display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 18}}>{items.map((item, index) => <div key={item.name} style={{...staggerStack(useCurrentFrame(), index, start), borderLeft: `8px solid ${item.tone === 'out' ? FEE_COLORS.out : item.tone === 'doubtful' ? FEE_COLORS.warning : FEE_COLORS.teamA}`, padding: 18, background: 'rgba(255,255,255,.32)'}}><div style={{fontFamily: 'Arial Black, Arial, sans-serif', fontSize: 28}}>{item.name}</div><div style={{fontSize: 20, marginTop: 8, textTransform: 'uppercase'}}>{item.status}</div></div>)}</div>;

export const DataSourceLabel: React.FC<{provider: string; asOf: string}> = ({provider, asOf}) => <div style={{position: 'absolute', bottom: 28, left: 80, color: FEE_COLORS.muted, fontSize: 15}}>Source · {provider} · updated {asOf}</div>;
