import assert from 'node:assert/strict';
import {compileAssetPrompt} from '../engine/src/assetPlanner';
import {validateSceneDocument, validateScene} from '../engine/src/schema';
import {selectPattern, sceneFromNarration} from '../engine/src/selector';
import {demoSceneDocument} from '../engine/src/demoData';
import {mapPointToCrop, orientPoint} from '../engine/src/tactical/geometry';
import {positionForPlayer} from '../engine/src/tactical/motion';

const valid = validateSceneDocument(demoSceneDocument);
assert.equal(valid.valid, true, valid.errors.join('\n'));
assert.equal(selectPattern('过去五场状态如何？').pattern, 'FORM-01');
assert.equal(selectPattern('问题出现在这个空间').pattern, 'TACT-03');
assert.equal(sceneFromNarration({narration: '关键对位是谁？'}).pattern, 'DUEL-01');
assert.ok(compileAssetPrompt({type: 'SUB-PLAYER', subject: 'Bukayo Saka'}).includes('NO TEXT'));
assert.ok(validateScene({...demoSceneDocument.scenes[0], motionPreset: ['not-a-preset']} as unknown).length > 0);
assert.deepEqual(orientPoint({x: 0.2, y: 0.4}, 'right-to-left'), {x: 0.8, y: 0.4});
assert.deepEqual(mapPointToCrop({x: 0.75, y: 0.5}, {x: 0.5, y: 0, width: 0.5, height: 1}, 'left-to-right'), {x: 0.5, y: 0.5});
assert.deepEqual(mapPointToCrop({x: 0.75, y: 0.5}, {x: 0.5, y: 0, width: 0.5, height: 1}, 'right-to-left'), {x: 0.5, y: 0.5});
const movementState = positionForPlayer(27, {id: 'saka', label: '7', position: {x: 0.8, y: 0.2}, team: 'A'}, [{id: 'move', playerId: 'saka', action: 'inside-run', from: {x: 0.8, y: 0.2}, to: {x: 0.6, y: 0.4}, startFrame: 18, durationInFrames: 18}]);
assert.ok(movementState.point.x < 0.8 && movementState.point.x > 0.6);
assert.equal(validateScene({...demoSceneDocument.scenes[6], tactical: {theme: 'mono-focus', players: [], movements: [{id: 'bad', playerId: 'missing', action: 'teleport', from: {x: 0, y: 0}, to: {x: 1, y: 1}, startFrame: 0, durationInFrames: 10}]}} as unknown).some((error) => error.includes('action is invalid')), true);
console.log('Smoke tests passed: schema, selector, and asset prompt invariants.');
